# Generated by Django 3.2.8 on 2023-02-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_auto_20230209_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinputdataset',
            name='answer',
        ),
    ]
